// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp5VnWfczmfb1fLRdL4__TjpiOUnxygxc',
    appId: '1:977038315313:web:3dfcc0bca71b72433e6a10',
    messagingSenderId: '977038315313',
    projectId: 'kfc-app-ff40b',
    authDomain: 'kfc-app-ff40b.firebaseapp.com',
    storageBucket: 'kfc-app-ff40b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_oU67LHziUz7Pzq41u2mm0QEL9zR633Q',
    appId: '1:977038315313:android:ad82f8b40780b8a23e6a10',
    messagingSenderId: '977038315313',
    projectId: 'kfc-app-ff40b',
    storageBucket: 'kfc-app-ff40b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Ps-xTM7yFWk048QLW5QgfP5zbQoAXBo',
    appId: '1:977038315313:ios:5ccee29d06b2ad833e6a10',
    messagingSenderId: '977038315313',
    projectId: 'kfc-app-ff40b',
    storageBucket: 'kfc-app-ff40b.firebasestorage.app',
    iosBundleId: 'com.example.kfc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Ps-xTM7yFWk048QLW5QgfP5zbQoAXBo',
    appId: '1:977038315313:ios:5ccee29d06b2ad833e6a10',
    messagingSenderId: '977038315313',
    projectId: 'kfc-app-ff40b',
    storageBucket: 'kfc-app-ff40b.firebasestorage.app',
    iosBundleId: 'com.example.kfc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp5VnWfczmfb1fLRdL4__TjpiOUnxygxc',
    appId: '1:977038315313:web:f2d4f46e08c945503e6a10',
    messagingSenderId: '977038315313',
    projectId: 'kfc-app-ff40b',
    authDomain: 'kfc-app-ff40b.firebaseapp.com',
    storageBucket: 'kfc-app-ff40b.firebasestorage.app',
  );
}
